#!/usr/bin/env bash
# Capture schema drift — changes made directly in the database that are not yet in the
# migration files — into a new migration, using `supabase db diff`. Scoped to one
# project's schema and written into that project's migrations folder.
#
#   scripts/db-diff.sh <platform|<app-name>> <migration_name>
#   e.g. scripts/db-diff.sh goals add_test_column
#        scripts/db-diff.sh platform add_audit_index
#
# The diff compares the migration history (applied to a throwaway shadow DB) against the
# live database, so it only captures what you changed directly in the DB. Override the
# diffed schema with SIS27_DIFF_SCHEMA=... (defaults: platform -> public, <app> -> app_<app>).
#
# Review the generated SQL before committing: `db diff` (migra) captures schema structure —
# tables, columns, constraints, indexes, RLS policies, grants, functions, triggers, views —
# but NOT comments or table data (it is schema-only).
set -euo pipefail
SIS27_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SIS27_ROOT/scripts/lib-db.sh"

target="${1:-}"; name="${2:-}"
if [[ -z "$target" || -z "$name" ]]; then
  echo "Usage: $0 <platform|<app-name>> <migration_name>" >&2
  echo "  e.g. $0 goals add_test_column" >&2
  exit 1
fi

case "$target" in
  platform|root|sis27) workdir="$SIS27_ROOT"; schema="public" ;;
  *)
    workdir="$SIS27_ROOT/apps/$target"
    if [[ ! -f "$workdir/supabase/config.toml" ]]; then
      echo "No Supabase project at apps/$target (expected apps/$target/supabase/config.toml)." >&2
      exit 1
    fi
    schema="app_$target"
    ;;
esac
schema="${SIS27_DIFF_SCHEMA:-$schema}"

# Build the combined history so the shadow has platform + all apps (apps depend on public).
assemble_migrations

echo "Diffing schema '$schema' (migration history -> live database)..." >&2
diff_sql="$("${SUPABASE_CMD[@]}" db diff \
  --workdir "$SIS27_MIGRATE_STAGE" \
  --db-url "$DB_URL" \
  --schema "$schema" 2>/dev/null)"

if ! grep -q '[^[:space:]]' <<<"$diff_sql"; then
  echo "No drift: schema '$schema' already matches the migrations. Nothing written." >&2
  exit 0
fi

# Let the CLI mint the timestamped file in the target project, then fill it with the diff.
created_msg="$("${SUPABASE_CMD[@]}" migration new --workdir "$workdir" "$name" 2>&1)"
rel="$(sed -n 's/.*Created new migration at //p' <<<"$created_msg" | tr -d '\r')"
file="$workdir/$rel"
if [[ -z "$rel" || ! -f "$file" ]]; then
  echo "ERROR: could not locate the migration file the CLI created:" >&2
  echo "$created_msg" >&2
  exit 1
fi

{
  echo "-- Generated by scripts/db-diff.sh from live DB drift in schema '$schema'."
  echo "-- Review before committing: db diff captures structure, RLS policies and grants, but not comments or data."
  echo
  printf '%s\n' "$diff_sql"
} >"$file"

echo "Wrote $file" >&2
echo "$file"
